name: halo_api_commander
description: A sample command-line application.
version: 1.0.1
repository: https://github.com/MaelMbange/halo_api_commander

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  image: ^4.1.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
